### ISSUE TITLE
Translation: use translation keys in pug templates (STATIC)

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/YiMovi#101]

**Comment by njsfield** [comment]
Instead of combining the `#{__('app.thing')` syntax with regular string literal syntax, the JSON lang files can simply be required via middleware, then a 'static' key can be added to the locals object for routes to consume...

```javascript
exports.initStatic = (req, res, next) => {
  res.locals.static = require(`../locales/${res.locale}.json`);
  next();
};
```
