### ISSUE TITLE
Translation: optimise templates for Chinese language

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/YiMovi#103]

**Comment by njsfield** [comment]
https://medium.com/@bobtung/best-practice-in-chinese-layout-f933aff1728f - quite detailed introduction to a lot of considerations 

The `:lang` css pseudo can be helpful (see [here](https://www.w3.org/International/questions/qa-css-lang))

If we first focus on adjusting font styling for Chinese letters, we could begin by simply changing the lang attribute in the topmost `html` element, then add base rules to the document...

```css
html:lang(chn) 	{
    font-size: .8rem
    }
```

Rough example, but could help prevent if/else logic in our pug templates that apply different classes
