### ISSUE TITLE
Misc Issues

### ISSUE THREAD

**Issue by njsfield** [InFact-coop/YiMovi#107]
- [x] Make cleaner tachyons build solution, perhaps [this](https://github.com/andrewMacmurray/tachyons-setup)
- [x] refactor variables that are shared across views into middleware (e.g. keystone utils, maybe also page titles, maybe also colors?)

**Comment by emilyb7** [comment]
Example of how to make stuff available across all views

In `routes/index.js` - under common middleware

```js
keystone.pre('routes', function (req, res, next) {
  res.locals._ = require('lodash');
  next();
});
```

**Comment by njsfield** [comment]
Sweet! The full URL address should be added as a key to locals, and keystone utils too.
For colours- a function call be executed in this middleware method to determine what`local.color` will be for the route/route. This same approach can be used for page titles.

Pug views should not create this data themselves and shouldn't contain this logic, they should be given the data from the top (this way we'll only need to change colours/titles in one location). I'll make an issue for this
