### ISSUE TITLE
Set up nightwatch

### ISSUE THREAD

**Issue by njsfield** [InFact-coop/YiMovi#111]
- [ ] set up config file
- [ ] set tear up / down for server + nightwatch

**Comment by njsfield** [comment]
Explore headless chrome nightwatch

**Comment by njsfield** [comment]
assigned to @des-des, will use branch **nightwatch** boilerplate which I've started to set up

**Comment by des-des** [comment]
@njsfield @emilyb7 

I see a deploy script looking something like this:
```bash
git checkout master && npm run test.e2e && git checkout production && git merge master && git push origin production
```

Then you can set up heroku instance to watch production branch on gh
