### ISSUE TITLE
Grey on yellow

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/YiMovi#121]
Currently really hard to read the gray text on the yellow background, e.g. here: /genres/cartoon

This becomes even worse when we change the names of the film titles (currently class .light-silver, which is not part of the original color scheme) to .light-gray

**Comment by njsfield** [comment]
The (not 50) shades of grey we are are generally very light, so any combination with yellow (saturated/darkened or not) will not contrast well together.

We can perhaps experiment with orange with high saturation and low brightness

**Comment by njsfield** [comment]
Used original colour scheme provided in style guide (as primary yellow was more of a darker shade of orange anyway)
