### ISSUE TITLE
Translation Spreadsheet 

### ISSUE THREAD

**Issue by njsfield** [InFact-coop/YiMovi#137]
For static text in views (non database retrieved), json fields will be populated with key/value pairs.
A spreadsheet will be made available for PO to write translations of english static content.
This spreadsheet will then need to be converted to json, so that english & chinese json files exist

**Comment by njsfield** [comment]
JSON files get saved in topmost `/locales` directory.
There should be;
- 1 file for english translations (en.json)
- 1 file for chinese translations (chn.json)

**Comment by njsfield** [comment]
English - 
```json
{
     "app": {
         "name": "YIMOVI EN"
     },
     "index" : {
         "title" : "Chinese film and the cross-cultural medical humanities",
         "byline1" : "What can the Sinophone world offer to the Medical Humanities?",
         "byline2" : "What can the Medical and Health Humanities offer to China?"
    }
 }
```
etc

**Comment by emilyb7** [comment]
To make this simpler:
- can't have multiline translation strings
- no nesting of json more than 1 object deep
- no arrays

As a result of which:
- need to fix keys for flash messages
- create new model for team members with english and chinese names

**Comment by emilyb7** [comment]
- [x] JSON >> CSV
- [x] CSV >> JSON

**Comment by emilyb7** [comment]
Actual spreadsheet created, saved in Google docs, sent to Vivienne.
