### ISSUE TITLE
Contact form page

### ISSUE THREAD

**Issue by emilyb7** [InFact-coop/YiMovi#93]
Create new page and link from site footer

**Comment by njsfield** [comment]
@emilyb7 any more info about the specs for this form? Form fields needed, design etc?

**Comment by emilyb7** [comment]
@njsfield no specs for the design. For what fields to include I would look at a few other sites and follow normal conventions. The form needs to be clearly linked from around the site, probably via the footer. And we need some nice inviting text. I think you're free to do what you think is best :)
